

spring:
  application:
    name: dynamic-tp-zookeeper-demo
  # ?????zk???????
  dynamic:
    tp:
      config-type: properties # zookeeper???properties??
      zookeeper:
        #        config-version: 1.0.0 # ?????
        zk-connect-str: 127.0.0.1:2181 # zk???????????????
        root-node: /configserver/userproject # ????
        node: dynamic-tp-zookeeper-demo # ??????
      log-path: D:\log

  rabbitmq:
    host: 192.168.23.133
    username: guest
    password: guest
    virtual-host: /
    port: 5672
    listener:
      simple:
        #??????
        concurrency: 10
        max-concurrency: 10
        #??????????????? ???????????
        prefetch: 1
        #???????????
        auto-startup: true
        default-requeue-rejected: true
    template:

      #??????
      retry:
        enabled: true
        initial-interval: 1000ms
        max-attempts: 3
        max-interval: 1000ms
        multiplier: 1
    #新加入 和动态线程池相关



  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cardgame?useUnicode=true&&characterEncoding=UTF-8&&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

  redis:
    host: 192.168.23.133
    port: 6379
    database: 0
    connect-timeout: 10000ms

mybatis:
  #    mapper-locations: classpath:mapper/*.xml
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: com.cardgameserver.entity
server:
  port: 8890

# ??prometheus
management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: '*'